export default {
  info: {
    name: '韩毅',
    gender: '男',
    age: 26,
    position: '前端开发工程师',
    workingYears: 3,
    phoneNumber: '15679112682',
    email: '2387870957@qq.com',
    picture: '/hanyi.jpg',
  },
  skills: {
    icons: [
      '/javascript.svg',
      '/typescript.svg',
      '/react.svg',
      '/redux.svg',
      '/react-router.svg',
      '/antd.svg',
      '/vite.svg',
      '/webpack.svg',
      '/rollup.svg',
      '/babel.svg',
      '/axios.svg',
      '/nodejs.svg',
      '/git.svg',
      '/npm.svg',
      '/etc.svg',
    ],
    descriptions: [
      '熟悉 PC、H5 和小程序开发，能够准确还原设计稿，有处理响应式布局和兼容性问题的经验',
      '熟悉 ES6+ 常用语法，日常开发使用 TypeScript 提高代码可靠性和可维护性',
      '熟悉 React 技术栈和相关生态，包含 React Router、Redux 以及各类工具库的使用',
      '熟悉主流组件库和图表库使用及二次封装，例如 Ant Design、Ant Design Mobile、ECharts 等',
      '了解 Node.js 开发，能够使用 Express、Koa 等框架搭建后端服务，了解 RESTful API 设计',
      '具备网络请求的优化与封装能力，熟悉 fetch 和 Axios 的使用，了解 HTTP 网络协议',
      '具备项目构建与 Git 工作流经验，了解前端工程化，例如 Vite 和 Webpack 配置 plugin 和 loader',
      '具备代码质量意识，采用规范、重构、Lint、Code Review 等方式进行约束和优化',
      '具备良好英语水平，拥有六级证书，能够查阅官方文档，并在开发中规范命名',
    ],
  },
  experiences: [
    {
      type: 'company',
      icon: '/fliggy.svg',
      company: '易宝软件科技有限公司（阿里巴巴-飞猪旅行）',
      position: '前端开发工程师',
      time: '2024 年 05 月 - 2024 年 09 月',
      descriptions: [
        '负责飞猪旅行机票出行中后台、支付中后台、小蜜客服模板等业务迭代开发',
      ],
    },
    {
      type: 'company',
      icon: '/eleme.svg',
      company: '法本信息技术股份有限公司（阿里巴巴-饿了么）',
      position: '前端开发工程师',
      time: '2023 年 08 月 - 2024 年 03 月',
      descriptions: [
        '负责饿了么放心点·榜、VIP、拼团、小饿替你点等 C 端导购业务迭代开发',
        '针对业务所使用的集团内部框架和库，汇总并反馈相关 bug，提供相关 case 复现 demo',
      ],
    },
    {
      type: 'company',
      icon: '/wuitu.svg',
      company: '辉途智能科技有限公司',
      position: '前端开发工程师',
      time: '2021 年 03 月 - 2023 年 07 月',
      descriptions: [
        '负责牛轻松牧场管理系统 WEB 和 APP，以及内部运营配置平台迭代开发',
        '基于 Node-Red 并结合业务场景，模拟牛舍内网关、操作设备和传感器工作流程，提高测试效率',
      ],
    },
    {
      type: 'education',
      icon: '/NCHU.svg',
      school: '南昌航空大学（本科）',
      degree: '本科',
      major: '通信工程',
      time: '2016 年 09 月 - 2020 年 07 月',
      descriptions: [
        '专业排名 23 / 103，曾获数学建模省奖、校级奖学金等'
      ],
    },
  ],
  projects: [
    {
      type: 'close',
      icon: '/react.svg',
      name: '飞猪机票出行中后台',
      description:
        '包含出行服务各项配置能力，致力于优化机票经营流程、提升运营研发服务体验，为日常经营活动提供一站式解决方案',
      stack: [
        'React',
        'Ant Design',
        'Umi',
        'Midway',
        'ahooks',
      ],
      details: [
        '✨ 负责应急取数、事件反馈、排查工具、航司规则等页面或功能模块的开发与调整',
        '📦 基于 Card 组件封装表单自定义模块，支持点击或拖拽的上下排序功能',
        '📦 基于 deepInsight 和 Drawer 组件封装数据可视化组件，并调研使用 iframe 的情况下能否自定义全局筛选器传参方案',
        '📦 基于 useRequest 封装获取表格数据并联动表单的自定义 hook，支持数据格式化转换、抹平接口返回值结构差异、状态管理等功能特性',
        '⚙️ 重构 Layout 的 Header 模块，增加国内国际、预发线上的不同组合下的环境切换功能，同时兼容开发运营人员已有的历史记录',
        '⚡️ 优化出发到达城市、机场这类包含分隔符的标签形式 Select 组件，增加扩展菜单控制 OD 输入，解决运营人员在手动输入大量选项时存在的用户体验问题',
        '⚡️ 部分复杂度较低的列表页使用低代码平台搭建或使用 Form Render 生成表单，提高开发效率',
        '🛠️ 配置 HSFClient，指定 Provider ip，解决后端因为特殊情况而无法部署主预发环境时，需要指定服务器的接口调用问题',
        '🐛 解决将该后台迁移至机票经营中后台（微前端架构）作为子应用时的各类问题，例如主应用 antd 版本为 4，为避免样式冲突需将基于 antd 5 特有的组件、功能特性进行修改适配',
      ],
    },
    {
      type: 'close',
      icon: '/react.svg',
      name: '代号 Forge',
      description:
        '本项目是为了学习 Node.js 的 demo（同时独立开发前端和后端部分），功能将围绕习惯打卡进行开发，旨在帮助用户养成良好的各类习惯',
      stack: [
        'React',
        'Vite',
        'Ant Design',
        'Express',
        'Sequelize',
        'MySQL',
      ],
      details: [
        '✨ 基于 Node.js 和 Express 搭建后端服务，使用 Sequelize 操作 MySQL 数据库，实现注册登录、习惯增删改查等接口',
        '📦 封装接口认证中间件，通过验证 JWT Token 实现对用户身份的验证与权限控制',
        '💅 使用 bcryptjs 对用户密码等敏感数据进行加密，增强用户信息安全',
        '🛠️ 配置 CORS 解决本地开发中的跨域问题，避免使用 Vite proxy 或 Nginx 的缺点',
        '🛠️ 使用 Docker 管理 MySQL 数据库环境，从而保持本地的开发环境与服务器环境一致',
      ],
    },
    {
      type: 'close',
      icon: '/react.svg',
      name: '饿了么 放心点·榜',
      description:
        '放心点·榜是饿了么店铺、商品榜和营养榜等一系列榜单 IP 统称，作为导购效率和B端资源撬动产品，日均 pv 在百万量级，基于 Hybrid 混合开发，落地页为 H5 版本',
      stack: [
        'React',
        'Ice',
        'Ant Design Mobile',
        'Weex',
        'EBridge',
        'WindVane',
        'HybridAPI',
        'ahooks',
      ],
      details: [
        '✨ 负责所有餐饮类榜单落地页迭代开发，以及搭建零售商品榜落地页',
        '📦 封装双列分栏弹窗组件，支持侧边栏和内容区自动选中类目并滚动至可视区域的交互效果',
        '📦 封装图文 Tab 栏和全部类目浮层组件，支持点击锚点和上滑吸顶效果，以及异常数据过滤展示',
        '📦 封装各模块数据清洗函数 adapter，包含接口异常兜底和数据重组',
        '📦 封装 dataStore，实现缓存逻辑，提升用户体验，可通过 url 参数动态开启',
        '📦 封装工具函数，例如基于 lodash 实现加载更多数据时的防抖处理、判断设备端类型、rpx 转 px',
        '⚡️ 优化主接口请求 hook，监听各项参数触发 fetch，并包含超时、loading 以及错误兜底逻辑',
        '⚙️ 重构部分模块，例如店铺卡片列表使用 useMemo、useCallback、memo 进行优化，提高性能',
        '💅 基于 EBridge 调用饿了么 APP Native 能力，例如获取地理位置信息、经纬度参数等',
        '💅 基于 WindVane 和 HybridAPI 开发全局导航栏，同时适配饿了么 APP 和支付宝小程序',
        '💅 基于 ltracker 封装埋点组件、基于 exlog 实现异常监控上报',
        '💅 基于 postcss-px-to-viewport 实现响应式布局',
        '💅 使用 react-infinite-scroller 滚动容器实现上滑加载、回调触发距离、loader 展示、动态样式等',
        '🐛 处理双端各机型兼容性问题，例如 IOS 端在页面返回时 tab 栏不吸顶、各机型滚动穿透问题等',
        '🛠️ 根据 AB 实验方案设置不同版本样式和相应功能，并调整请求链路逻辑及参数',
        '🛠️ 配置 webpack，实现文件维度条件编译以兼容 weex 版本，处理相关 bug 并汇总反馈',
        '💡 基于内部二维码平台，提供测试所需的榜单二维码生成规则，包含环境选项和各项请求参数配置',
      ],
    },
    {
      type: 'close',
      icon: '/react.svg',
      name: '饿了么 VIP',
      description:
        'VIP 是饿了么针对高净值人群提供专属表达和服务，基于 Hybrid 混合开发，落地页为 H5 版本',
      stack: [
        'React',
        'Ice',
        'Weex',
        'EBridge',
        'WindVane',
        'HybridAPI',
        'ahooks',
      ],
      details: [
        '✨ 负责搭建身份详情页以及开卡主链路',
        '📦 封装具有较为复杂动画效果的权益卡片组件、封装全局上下文 hook 实现 toast 提示',
        '💅 基于唤端 SDK 开发微信过桥页，展示下载提示弹窗或唤起饿了么 APP，并通过端外验证 token 以展示不同文案，提升用户体验；基于 WindVane 实现领卡成功后通知 Native 刷新皮肤',
        '🐛 处理双端兼容性问题，例如安卓端部分机型浏览器版本不支持 Object.fromEntries 导致 crash',
      ],
    },
  ],
};


// export default {
//   info: {
//     name: '陈京璐',
//     gender: '女',
//     age: 27,
//     position: '前端开发工程师',
//     workingYears: 3,
//     phoneNumber: '18789055297',
//     email: '2320035651@qq.com',
//     picture: '/jinglu.jpg',
//   },
//   skills: {
//     icons: [
//       '/javascript.svg',
//       '/typescript.svg',
//       '/react.svg',
//       '/redux.svg',
//       '/react-router.svg',
//       '/antd.svg',
//       '/vite.svg',
//       '/webpack.svg',
//       '/rollup.svg',
//       '/babel.svg',
//       '/axios.svg',
//       '/nodejs.svg',
//       '/git.svg',
//       '/npm.svg',
//       '/etc.svg',
//     ],
//     descriptions: [
//       '熟悉 PC、H5 和小程序开发，能够准确还原设计稿，有处理响应式布局和兼容性问题的经验',
//       '熟悉 ES6+ 常用语法，日常开发使用 TypeScript 提高代码可靠性和可维护性',
//       '熟悉 React 技术栈和相关生态，包含 React Router、Redux 以及各类工具库的使用',
//       '熟悉主流组件库和图表库使用及二次封装，例如 Ant Design、Ant Design Mobile、ECharts 等',
//       '具备网络请求的优化与封装能力，熟悉 fetch 和 Axios 的使用，了解 HTTP 网络协议',
//       '具备项目构建与 Git 工作流经验，了解前端工程化，例如 Vite 和 Webpack 配置 plugin 和 loader',
//       '具备代码质量意识，采用规范、重构、Lint、Code Review 等方式进行约束和优化',
//       '具备良好英语水平，能够查阅官方文档，并在开发中规范命名',
//     ],
//   },
//   experiences: [
//     {
//       type: 'company',
//       icon: '/fliggy.svg',
//       company: '易宝软件科技有限公司（阿里巴巴-飞猪旅行）',
//       position: '前端开发工程师',
//       time: '2024 年 05 月 - 2024 年 09 月',
//       descriptions: [
//         '负责北京环球度假区小程序和中后台业务迭代开发，参与内部知识库技术文档沉淀',
//         '因九月底项目组整体搬迁至杭州，目前在职看机会，可随时入职',
//       ],
//     },
//     {
//       type: 'company',
//       icon: '/jiyue.jpg',
//       company: '软通动力信息技术股份有限公司（极越汽车）',
//       position: '前端开发工程师',
//       time: '2023 年 04 月 - 2024 年 03 月',
//       descriptions: [
//         '负责极越汽车营销管理中后台业务迭代开发',
//       ],
//     },
//     {
//       type: 'company',
//       icon: '/wuitu.svg',
//       company: '辉途智能科技有限公司',
//       position: '前端开发工程师',
//       time: '2021 年 03 月 - 2023 年 02 月',
//       descriptions: [
//         '负责牛轻松牧场管理系统 Web 和 APP，以及内部运营配置平台迭代开发',
//       ],
//     },
//     {
//       type: 'company',
//       icon: '/airplane.svg',
//       company: '上航假期北京国际旅行社有限公司',
//       position: 'UI 设计师',
//       time: '2017 年 09 月 - 2020 年 05 月',
//       descriptions: [
//         '负责机票出票、成团管理系统 UI 设计，参与制定相关设计规范',
//         '负责旅游宣传相关平面设计，在职期间设计并印发 50 余版线上、线下宣传海报以及立式海报',
//       ],
//     },
//     {
//       type: 'education',
//       icon: '/bit.webp',
//       school: '北京理工大学',
//       degree: '本科',
//       major: '',
//       time: '2021 年 07 月 - 2023 年 06 月',
//       descriptions: [
//         '自考本科，论文已通过'
//       ],
//     },
//     {
//       type: 'education',
//       icon: '/hnasatc.webp',
//       school: '三亚航空旅游职业学院',
//       degree: '本科',
//       major: '',
//       time: '2015 年 09 月 - 2018 年 07 月',
//       descriptions: [
//       ],
//     },
//   ],
//   projects: [
//     {
//       type: 'close',
//       icon: '/alipay.svg',
//       name: '北京环球度假区小程序',
//       description:
//         '本项目旨在为游客提供便捷的一站式服务，覆盖票务处理、酒店预订、园区地图导览、会员服务与活动资讯等全方位需求',
//       stack: [
//         '支付宝小程序开发框架',
//         'Ant Design Mini',
//       ],
//       details: [
//         '✨ 负责优速通、快速入园卡、套餐打包等票务的正向与逆向交易链路',
//         '📦 封装 SKU 时间段与场次选择弹窗组件，包含购买数量和时间点是否超时校验、对应日期下判断各时间段或场次是否可选并置灰禁用等功能',
//         '📦 封装各功能模块数据清洗函数，包含接口异常兜底、数据排序和重组等功能',
//         '📦 封装针对特定数据结构，生成对应内容弹窗所需展示状态和富文本的工具函数',
//         '⚙️ 重构部分模块，例如票型详情页面代码拆分以减少耦合提高可维护性',
//         '⚡️ 优化用户体验，例如针对日历折叠面板与底部滚动容器结合时出现的滚动问题，调整触发区域',
//       ],
//     },
//     {
//       type: 'close',
//       icon: '/react.svg',
//       name: '北京环球度假区中后台',
//       description:
//         '本项目旨在为北京环球度假区提供支付宝小程序的各项功能配置与运营需求。系统覆盖了从票务管理、产品打包、数据监控到用户体验优化的全方位业务流程',
//       stack: [
//         'React',
//         'Umi',
//         'Ant Design',
//         'Redux',
//         'ahooks',
//       ],
//       details: [
//         '✨ 负责票种票型、点位配置、打包管理、基础数据管理、标签库等功能模块开发',
//         '📦 封装手机模拟器组件，用于模拟 IPhone 手机的外观并显示实时的时间、电量状态以及可自定义的内容区域',
//         '📦 基于 React-Diff-Viewer 和 Drawer 封装修改历史记录的 JSON diff 组件，用于展示和比较不同版本的配置信息，便于追踪修改历史',
//         '📦 基于 braft-editor 封装富文本编辑器组件，增强了编辑器的功能性和易用性，满足了内容创建和编辑的需求',
//         '📦 封装 File 转 base64、以及文件下载函数，使用者无需关心下载资源是否会跨域，函数内会抹平',
//         '📦 封装安全解析 JSON 字符串的工具函数，解决大数精度丢失问题，保证了数据的准确性和安全性',
//         '⚙️ 重构部分模块，例如使用 Form Render 优化各项表单，减少冗余代码量，提高开发效率',
//         '🐛 优化请求函数 hook，增加特殊情况下的错误异常处理逻辑，提高系统的稳定性',
//       ],
//     },
//     {
//       type: 'close',
//       icon: '/vue.svg',
//       name: '极越汽车 营销管理系统',
//       description:
//         '本项目旨在促进极越汽车品牌传播、挖掘用户需求，实现个性化服务，从而增强用户粘性，并推动销售增长。包含裂变营销、常态邀请、用户触达、用户权益等功能',
//       stack: [
//         'Vue 3',
//         'Vite',
//         'Ant Design Vue',
//         'Vue Router',
//         'Pinia',
//         'VueUse',
//       ],
//       details: [
//         '✨ 负责 H5 营销页面配置、用户触达、裂变活动等功能模块开发',
//         '📦 封装活动页搭建组件，可联动相关活动类型获取不同模板，并根据配置项在画布展示对应内容，快速生成营销 H5 页面',
//         '📦 封装通用组件，例如图片上传组件，自动提示上传规范（尺寸与大小），并搭配轮播图组件，大幅提升活动页配置的便捷性与视觉效果',
//         '📦 封装工具函数，例如 RGB 颜色值转换为十六进制颜色值、数组转符合 antd Select 标准的 options 类型',
//         '⚙️ 重构部分模块，例如活动编辑表单将改为可扩展节点列表，支持上下移动、删除、新增等操作和可拖拽效果',
//         '⚡️ 优化系统性能，例如减少冗余请求、使用 watch 和 computed 优化数据加载与渲染流程等',
//       ],
//     },
//     {
//       type: 'close',
//       icon: '/vue.svg',
//       name: '牛轻松 牧场管理系统',
//       description:
//         '本项目旨在为奶牛养殖业的精细化运营能力，包含牧场、牛舍、人员、设备等管理功能。可在线监控牧场、牛舍各项数据指标，及时通知告警相关人员，并能根据需要控制各类智能硬件',
//       stack: [
//         'Vue 3',
//         'Vite',
//         'Arco Design',
//         'Vue Router',
//         'Pinia',
//         'VueUse',
//       ],
//       details: [
//         '✨ 开发并维护 30+ 页面和组件，例如产奶分析、牛群管理、设备管理、事件配置等功能模块',
//         '🆕 迁移旧平台，例如网关和设备管理页面，并在原有基础上增加新功能，如表格编辑，以及不同网关下的可编辑字段等',
//         '📦 封装通用组件，例如基于腾讯地图封装地图组件，并用于内部的牛只定位测试工具',
//         '📦 封装工具函数，例如基于 dayjs 封装处理日期时间函数，基于 lodash 封装深拷贝函数',
//         '📦 封装全局样式，减少样式重复，提高开发效率，例如常用 flex 布局、页面容器、背景毛玻璃效果',
//         '⚙️ 重构部分模块，例如将设备类型从使用字典映射改为兼容新的查询接口',
//         '⚡️ 优化用户体验，例如环境配置模块中一键同步到其他牛舍选项',
//         '🐛 基于 Pinia 实现状态管理，例如全局的牧场切换功能，解决不同组件无法监听 localStorage 中的牧场 ID 变化的问题',
//         '💅 基于 ECharts 开发常见图表，并能根据不同选项和时间动态更新数据',
//         '💅 修改请求响应拦截器，例如在请求头中添加当前牧场 ID 用于鉴权，全局处理分页、排序等参数等',
//       ],
//     },
//   ],
// };
